"""
수집기 테스트.

GNEWS_SEARCH_RESPONSE / GNEWS_EMPTY_RESPONSE는 2026-08-03에 실제 GNews API를
호출해 받은 응답이다. 본문만 길이 때문에 줄였고 구조는 손대지 않았다.
"""
from __future__ import annotations

from datetime import datetime, timezone
from uuid import uuid4

import pytest

from src.collectors import fetchers
from src.pipeline_common.models import CollectRequest

# 실제 응답: q=semiconductor&lang=en&max=3
GNEWS_SEARCH_RESPONSE = {
    "information": {
        "realTimeArticles": {
            "message": "Real-time news data is only available on paid plans. "
            "Free plan has a 12-hour delay."
        }
    },
    "totalArticles": 16645,
    "articles": [
        {
            "id": "e58e114e256c40eb16c3bb8001788a0d",
            "title": "Wall Street's favorite bet comes undone as chips whipsaw market",
            "description": "Semiconductor stocks posted their worst monthly performance...",
            "content": "The one-way trade in semiconductor stocks... [5481 chars]",
            "url": "https://www.moneycontrol.com/news/business/markets/wall-street-s-favorite-bet-13991314.html",
            "image": "https://images.moneycontrol.com/static-mcnews/2026/07/x.jpg",
            "publishedAt": "2026-08-02T13:50:15Z",
            "lang": "en",
            "source": {
                "id": "fd3677545b80d5db7541de8e111d27ba",
                "name": "Moneycontrol",
                "url": "https://www.moneycontrol.com",
                "country": "in",
            },
        },
        {
            "id": "1c14023288db8f6e3a1ae40a40d6d5db",
            "title": "AI predicts Nvidia stock price for August 31, 2026",
            "description": "A new Nvidia stock forecast generated by ChatGPT...",
            "content": "A new Nvidia (NASDAQ: NVDA) stock forecast... [2540 chars]",
            "url": "https://finbold.com/ai-predicts-nvidia-stock-price-for-august-31-2026/",
            "image": "https://assets.finbold.com/uploads/2026/08/x.webp",
            "publishedAt": "2026-08-02T12:09:07Z",
            "lang": "en",
            # 한국어 응답에는 country가 없었다. 없어도 동작해야 한다.
            "source": {
                "id": "72ea416416ab0eec8fe687d6262961e8",
                "name": "Finbold",
                "url": "https://finbold.com",
            },
        },
    ],
}

# 실제 응답: q=반도체&lang=ko -> 요금제 제약으로 전부 잘려나간 경우
GNEWS_EMPTY_RESPONSE = {
    "information": {
        "realTimeArticles": {
            "message": "Real-time news data is only available on paid plans. "
            "Free plan has a 12-hour delay."
        }
    },
    "articlesRemovedFromResponse": {
        "historicalArticles": {
            "message": "1 article was removed from the response because historical data "
            "beyond 30 days is only available on paid plans."
        }
    },
    "totalArticles": 1,
    "articles": [],
}

ARTICLE_HTML = b"<html><body><article><p>chip demand</p></article></body></html>"


class _FakeResponse:
    def __init__(self, payload: dict, status_code: int = 200) -> None:
        self._payload = payload
        self.status_code = status_code

    def json(self) -> dict:
        return self._payload


@pytest.fixture
def gnews_source() -> dict:
    return {
        "id": str(uuid4()),
        "name": "gnews - semiconductor",
        "source_type": "news",
        "config": {"provider": "gnews", "query": "semiconductor", "request_delay_sec": 0},
    }


@pytest.fixture
def request_obj() -> CollectRequest:
    return CollectRequest(workspace_id=uuid4(), source_id=uuid4())


@pytest.fixture
def stub_article(monkeypatch: pytest.MonkeyPatch):
    """기사 원문 요청을 가로챈다. (요청주소 -> 최종주소) 매핑을 넘겨 리다이렉트를 흉내낸다."""

    def install(redirects: dict[str, str] | None = None):
        mapping = redirects or {}
        calls: list[str] = []

        def fake_http_get(url: str, source: dict):
            calls.append(url)
            return ARTICLE_HTML, "text/html", 200, mapping.get(url, url)

        monkeypatch.setattr(fetchers, "_http_get", fake_http_get)
        return calls

    return install


def _stub_gnews_api(monkeypatch: pytest.MonkeyPatch, payload: dict, status_code: int = 200) -> dict:
    """httpx.get을 가로채 GNews 응답을 대신 돌려준다. 전달된 파라미터를 남긴다."""
    import httpx

    captured: dict = {}

    def fake_get(url: str, **kwargs):
        captured["url"] = url
        captured["params"] = kwargs.get("params", {})
        return _FakeResponse(payload, status_code)

    monkeypatch.setattr(httpx, "get", fake_get)
    monkeypatch.setenv("GNEWS_API_KEY", "test-key-not-real")
    return captured


# ------------------------------------------------------------
# gnews 수집기
# ------------------------------------------------------------


def test_gnews_maps_response_fields(
    monkeypatch: pytest.MonkeyPatch, gnews_source: dict, request_obj: CollectRequest, stub_article
) -> None:
    """실제 응답 구조를 그대로 파싱한다. country가 없는 항목도 처리한다."""
    _stub_gnews_api(monkeypatch, GNEWS_SEARCH_RESPONSE)
    stub_article()

    outcome = fetchers.fetch_gnews(gnews_source, request_obj)

    assert len(outcome.items) == 2
    first = outcome.items[0]
    # 문서 식별 기준은 언론사 원문 주소
    assert first.url.startswith("https://www.moneycontrol.com/")
    assert first.title_hint == "Wall Street's favorite bet comes undone as chips whipsaw market"
    assert first.published_at_hint == datetime(2026, 8, 2, 13, 50, 15, tzinfo=timezone.utc)
    assert first.content_type == "text/html"
    # source.country가 없는 두 번째 항목도 정상 처리
    assert outcome.items[1].url.startswith("https://finbold.com/")


def test_gnews_records_plan_limit_notices(
    monkeypatch: pytest.MonkeyPatch, gnews_source: dict, request_obj: CollectRequest, stub_article
) -> None:
    """요금제 제약으로 0건이 되면 사유가 남아야 한다. 조용히 넘어가면 원인을 못 찾는다."""
    _stub_gnews_api(monkeypatch, GNEWS_EMPTY_RESPONSE)
    stub_article()

    outcome = fetchers.fetch_gnews(gnews_source, request_obj)

    assert outcome.items == []
    assert any("12-hour delay" in n for n in outcome.notices)
    assert any("beyond 30 days" in n for n in outcome.notices)
    # 전체 건수는 있는데 받은 게 없다 -> 요금제 때문에 잘렸다는 표시
    assert outcome.skip_reasons.get("removed_by_plan_limit") == 1


def test_gnews_sends_expected_query_params(
    monkeypatch: pytest.MonkeyPatch, gnews_source: dict, stub_article
) -> None:
    """lang 기본값은 en, since는 from 파라미터로 넘어간다."""
    captured = _stub_gnews_api(monkeypatch, GNEWS_SEARCH_RESPONSE)
    stub_article()
    gnews_source["config"]["country"] = "us"

    fetchers.fetch_gnews(
        gnews_source,
        CollectRequest(
            workspace_id=uuid4(),
            source_id=uuid4(),
            since=datetime(2026, 7, 27, tzinfo=timezone.utc),
            limit=5,
        ),
    )

    params = captured["params"]
    assert captured["url"] == "https://gnews.io/api/v4/search"
    assert params["q"] == "semiconductor"
    assert params["lang"] == "en"
    assert params["country"] == "us"
    assert params["max"] == 5
    assert params["from"] == "2026-07-27T00:00:00Z"


def test_gnews_requires_api_key(
    monkeypatch: pytest.MonkeyPatch, gnews_source: dict, request_obj: CollectRequest
) -> None:
    monkeypatch.delenv("GNEWS_API_KEY", raising=False)
    with pytest.raises(fetchers.FetchError, match="GNEWS_API_KEY"):
        fetchers.fetch_gnews(gnews_source, request_obj)


# ------------------------------------------------------------
# news 제공자 분기
# ------------------------------------------------------------


def test_news_provider_defaults_to_naver(monkeypatch: pytest.MonkeyPatch) -> None:
    """provider를 안 적은 기존 소스는 그대로 네이버로 간다."""
    called: list[str] = []
    monkeypatch.setitem(
        fetchers._NEWS_PROVIDERS, "naver", lambda s, r: called.append("naver") or fetchers.FetchOutcome()
    )
    source = {"id": str(uuid4()), "name": "네이버", "source_type": "news", "config": {"query": "HBM"}}

    fetchers.fetch_news(source, CollectRequest(workspace_id=uuid4(), source_id=uuid4()))

    assert called == ["naver"]


def test_news_provider_rejects_unknown(request_obj: CollectRequest) -> None:
    source = {"id": str(uuid4()), "name": "x", "source_type": "news", "config": {"provider": "bing"}}
    with pytest.raises(fetchers.FetchError, match="알 수 없는 news provider"):
        fetchers.fetch_news(source, request_obj)


# ------------------------------------------------------------
# 설정값 읽기
# ------------------------------------------------------------


def test_zero_config_values_are_not_replaced_by_defaults() -> None:
    """
    0은 유효한 설정값이다. `conf.get(key) or default`로 읽으면 0을 넣어도
    기본값이 적용돼 요청 간격이 사라지지 않는다.
    """
    source = {"config": {"request_delay_sec": 0, "max_items": 0, "timeout_sec": 0}}

    assert fetchers._conf_number(source, "request_delay_sec", 1.0) == 0
    assert fetchers._conf_number(source, "max_items", 30) == 0
    assert fetchers._conf_number(source, "timeout_sec", 15.0) == 0
    # 키가 없을 때만 기본값
    assert fetchers._conf_number({"config": {}}, "request_delay_sec", 1.0) == 1.0


def test_zero_delay_actually_skips_sleep(monkeypatch: pytest.MonkeyPatch) -> None:
    slept: list[float] = []
    monkeypatch.setattr(fetchers.time, "sleep", lambda s: slept.append(s))

    fetchers._sleep_between_requests({"config": {"request_delay_sec": 0}})
    assert slept == []

    fetchers._sleep_between_requests({"config": {"request_delay_sec": 2}})
    assert slept == [2.0]


# ------------------------------------------------------------
# 리다이렉트 최종 주소
# ------------------------------------------------------------


def test_article_url_uses_final_redirect_target(
    monkeypatch: pytest.MonkeyPatch, gnews_source: dict, request_obj: CollectRequest, stub_article
) -> None:
    """
    구글 뉴스 RSS는 news.google.com 경유 주소를 준다. 그대로 저장하면 같은 기사가
    검색어마다 다른 문서로 쌓이므로, 리다이렉트 최종 주소를 문서 기준으로 쓴다.
    """
    _stub_gnews_api(monkeypatch, GNEWS_SEARCH_RESPONSE)
    google_link = GNEWS_SEARCH_RESPONSE["articles"][0]["url"]
    stub_article({google_link: "https://www.yna.co.kr/view/AKR20260802"})

    outcome = fetchers.fetch_gnews(gnews_source, request_obj)

    assert outcome.items[0].url == "https://www.yna.co.kr/view/AKR20260802"
