"""
수집기 테스트.

GNEWS_SEARCH_RESPONSE / GNEWS_EMPTY_RESPONSE는 2026-08-03에 실제 GNews API를
호출해 받은 응답이다. 본문만 길이 때문에 줄였고 구조는 손대지 않았다.
"""
from __future__ import annotations

import io
import zipfile
from datetime import datetime, timedelta, timezone
from uuid import uuid4

import pytest

from src.collectors import fetchers
from src.pipeline_common.models import CollectRequest, RawFetchResult

# 실제 응답: q=semiconductor&lang=en&max=3
GNEWS_SEARCH_RESPONSE = {
    "information": {
        "realTimeArticles": {
            "message": "Real-time news data is only available on paid plans. "
            "Free plan has a 12-hour delay."
        }
    },
    "totalArticles": 16645,
    "articles": [
        {
            "id": "e58e114e256c40eb16c3bb8001788a0d",
            "title": "Wall Street's favorite bet comes undone as chips whipsaw market",
            "description": "Semiconductor stocks posted their worst monthly performance...",
            "content": "The one-way trade in semiconductor stocks... [5481 chars]",
            "url": "https://www.moneycontrol.com/news/business/markets/wall-street-s-favorite-bet-13991314.html",
            "image": "https://images.moneycontrol.com/static-mcnews/2026/07/x.jpg",
            "publishedAt": "2026-08-02T13:50:15Z",
            "lang": "en",
            "source": {
                "id": "fd3677545b80d5db7541de8e111d27ba",
                "name": "Moneycontrol",
                "url": "https://www.moneycontrol.com",
                "country": "in",
            },
        },
        {
            "id": "1c14023288db8f6e3a1ae40a40d6d5db",
            "title": "AI predicts Nvidia stock price for August 31, 2026",
            "description": "A new Nvidia stock forecast generated by ChatGPT...",
            "content": "A new Nvidia (NASDAQ: NVDA) stock forecast... [2540 chars]",
            "url": "https://finbold.com/ai-predicts-nvidia-stock-price-for-august-31-2026/",
            "image": "https://assets.finbold.com/uploads/2026/08/x.webp",
            "publishedAt": "2026-08-02T12:09:07Z",
            "lang": "en",
            # 한국어 응답에는 country가 없었다. 없어도 동작해야 한다.
            "source": {
                "id": "72ea416416ab0eec8fe687d6262961e8",
                "name": "Finbold",
                "url": "https://finbold.com",
            },
        },
    ],
}

# 실제 응답: q=반도체&lang=ko -> 요금제 제약으로 전부 잘려나간 경우
GNEWS_EMPTY_RESPONSE = {
    "information": {
        "realTimeArticles": {
            "message": "Real-time news data is only available on paid plans. "
            "Free plan has a 12-hour delay."
        }
    },
    "articlesRemovedFromResponse": {
        "historicalArticles": {
            "message": "1 article was removed from the response because historical data "
            "beyond 30 days is only available on paid plans."
        }
    },
    "totalArticles": 1,
    "articles": [],
}

ARTICLE_HTML = b"<html><body><article><p>chip demand</p></article></body></html>"


class _FakeResponse:
    def __init__(self, payload: dict, status_code: int = 200, content: bytes = b"") -> None:
        self._payload = payload
        self.status_code = status_code
        self.content = content

    def json(self) -> dict:
        return self._payload


def _zip_bytes(inner_name: str, content: bytes) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr(inner_name, content)
    return buffer.getvalue()


@pytest.fixture
def gnews_source() -> dict:
    return {
        "id": str(uuid4()),
        "name": "gnews - semiconductor",
        "source_type": "news",
        "config": {"provider": "gnews", "query": "semiconductor", "request_delay_sec": 0},
    }


@pytest.fixture
def request_obj() -> CollectRequest:
    return CollectRequest(workspace_id=uuid4(), source_id=uuid4())


@pytest.fixture
def stub_article(monkeypatch: pytest.MonkeyPatch):
    """기사 원문 요청을 가로챈다. (요청주소 -> 최종주소) 매핑을 넘겨 리다이렉트를 흉내낸다."""

    def install(redirects: dict[str, str] | None = None):
        mapping = redirects or {}
        calls: list[str] = []

        def fake_http_get(url: str, source: dict):
            calls.append(url)
            return ARTICLE_HTML, "text/html", 200, mapping.get(url, url)

        monkeypatch.setattr(fetchers, "_http_get", fake_http_get)
        return calls

    return install


def _stub_gnews_api(monkeypatch: pytest.MonkeyPatch, payload: dict, status_code: int = 200) -> dict:
    """httpx.get을 가로채 GNews 응답을 대신 돌려준다. 전달된 파라미터를 남긴다."""
    import httpx

    captured: dict = {}

    def fake_get(url: str, **kwargs):
        captured["url"] = url
        captured["params"] = kwargs.get("params", {})
        return _FakeResponse(payload, status_code)

    monkeypatch.setattr(httpx, "get", fake_get)
    monkeypatch.setenv("GNEWS_API_KEY", "test-key-not-real")
    return captured


# ------------------------------------------------------------
# gnews 수집기
# ------------------------------------------------------------


def test_gnews_maps_response_fields(
    monkeypatch: pytest.MonkeyPatch, gnews_source: dict, request_obj: CollectRequest, stub_article
) -> None:
    """실제 응답 구조를 그대로 파싱한다. country가 없는 항목도 처리한다."""
    _stub_gnews_api(monkeypatch, GNEWS_SEARCH_RESPONSE)
    stub_article()

    outcome = fetchers.fetch_gnews(gnews_source, request_obj)

    assert len(outcome.items) == 2
    first = outcome.items[0]
    # 문서 식별 기준은 언론사 원문 주소
    assert first.url.startswith("https://www.moneycontrol.com/")
    assert first.title_hint == "Wall Street's favorite bet comes undone as chips whipsaw market"
    assert first.published_at_hint == datetime(2026, 8, 2, 13, 50, 15, tzinfo=timezone.utc)
    assert first.content_type == "text/html"
    # source.country가 없는 두 번째 항목도 정상 처리
    assert outcome.items[1].url.startswith("https://finbold.com/")


def test_gnews_records_plan_limit_notices(
    monkeypatch: pytest.MonkeyPatch, gnews_source: dict, request_obj: CollectRequest, stub_article
) -> None:
    """요금제 제약으로 0건이 되면 사유가 남아야 한다. 조용히 넘어가면 원인을 못 찾는다."""
    _stub_gnews_api(monkeypatch, GNEWS_EMPTY_RESPONSE)
    stub_article()

    outcome = fetchers.fetch_gnews(gnews_source, request_obj)

    assert outcome.items == []
    assert any("12-hour delay" in n for n in outcome.notices)
    assert any("beyond 30 days" in n for n in outcome.notices)
    # 전체 건수는 있는데 받은 게 없다 -> 요금제 때문에 잘렸다는 표시
    assert outcome.skip_reasons.get("removed_by_plan_limit") == 1


def test_gnews_sends_expected_query_params(
    monkeypatch: pytest.MonkeyPatch, gnews_source: dict, stub_article
) -> None:
    """lang 기본값은 en, since는 from 파라미터로 넘어간다."""
    captured = _stub_gnews_api(monkeypatch, GNEWS_SEARCH_RESPONSE)
    stub_article()
    gnews_source["config"]["country"] = "us"

    fetchers.fetch_gnews(
        gnews_source,
        CollectRequest(
            workspace_id=uuid4(),
            source_id=uuid4(),
            since=datetime(2026, 7, 27, tzinfo=timezone.utc),
            limit=5,
        ),
    )

    params = captured["params"]
    assert captured["url"] == "https://gnews.io/api/v4/search"
    assert params["q"] == "semiconductor"
    assert params["lang"] == "en"
    assert params["country"] == "us"
    assert params["max"] == 5
    assert params["from"] == "2026-07-27T00:00:00Z"


def test_gnews_requires_api_key(
    monkeypatch: pytest.MonkeyPatch, gnews_source: dict, request_obj: CollectRequest
) -> None:
    monkeypatch.delenv("GNEWS_API_KEY", raising=False)
    with pytest.raises(fetchers.FetchError, match="GNEWS_API_KEY"):
        fetchers.fetch_gnews(gnews_source, request_obj)


# ------------------------------------------------------------
# news 제공자 분기
# ------------------------------------------------------------


def test_news_provider_defaults_to_naver(monkeypatch: pytest.MonkeyPatch) -> None:
    """provider를 안 적은 기존 소스는 그대로 네이버로 간다."""
    called: list[str] = []
    monkeypatch.setitem(
        fetchers._NEWS_PROVIDERS, "naver", lambda s, r: called.append("naver") or fetchers.FetchOutcome()
    )
    source = {"id": str(uuid4()), "name": "네이버", "source_type": "news", "config": {"query": "HBM"}}

    fetchers.fetch_news(source, CollectRequest(workspace_id=uuid4(), source_id=uuid4()))

    assert called == ["naver"]


def test_news_provider_rejects_unknown(request_obj: CollectRequest) -> None:
    source = {"id": str(uuid4()), "name": "x", "source_type": "news", "config": {"provider": "bing"}}
    with pytest.raises(fetchers.FetchError, match="알 수 없는 news provider"):
        fetchers.fetch_news(source, request_obj)


# ------------------------------------------------------------
# 설정값 읽기
# ------------------------------------------------------------


def test_zero_config_values_are_not_replaced_by_defaults() -> None:
    """
    0은 유효한 설정값이다. `conf.get(key) or default`로 읽으면 0을 넣어도
    기본값이 적용돼 요청 간격이 사라지지 않는다.
    """
    source = {"config": {"request_delay_sec": 0, "max_items": 0, "timeout_sec": 0}}

    assert fetchers._conf_number(source, "request_delay_sec", 1.0) == 0
    assert fetchers._conf_number(source, "max_items", 30) == 0
    assert fetchers._conf_number(source, "timeout_sec", 15.0) == 0
    # 키가 없을 때만 기본값
    assert fetchers._conf_number({"config": {}}, "request_delay_sec", 1.0) == 1.0


def test_zero_delay_actually_skips_sleep(monkeypatch: pytest.MonkeyPatch) -> None:
    slept: list[float] = []
    monkeypatch.setattr(fetchers.time, "sleep", lambda s: slept.append(s))

    fetchers._sleep_between_requests({"config": {"request_delay_sec": 0}})
    assert slept == []

    fetchers._sleep_between_requests({"config": {"request_delay_sec": 2}})
    assert slept == [2.0]


# ------------------------------------------------------------
# 리다이렉트 최종 주소
# ------------------------------------------------------------


def test_article_url_uses_final_redirect_target(
    monkeypatch: pytest.MonkeyPatch, gnews_source: dict, request_obj: CollectRequest, stub_article
) -> None:
    """
    구글 뉴스 RSS는 news.google.com 경유 주소를 준다. 그대로 저장하면 같은 기사가
    검색어마다 다른 문서로 쌓이므로, 리다이렉트 최종 주소를 문서 기준으로 쓴다.
    """
    _stub_gnews_api(monkeypatch, GNEWS_SEARCH_RESPONSE)
    google_link = GNEWS_SEARCH_RESPONSE["articles"][0]["url"]
    stub_article({google_link: "https://www.yna.co.kr/view/AKR20260802"})

    outcome = fetchers.fetch_gnews(gnews_source, request_obj)

    assert outcome.items[0].url == "https://www.yna.co.kr/view/AKR20260802"


# ------------------------------------------------------------
# 네이버 API 에러 처리
# ------------------------------------------------------------

NAVER_AUTH_ERROR_RESPONSE = {
    "errorMessage": "NID AUTH Result Invalid (1000) : Authentication failed.",
    "errorCode": "024",
}

NAVER_SEARCH_RESPONSE = {
    "lastBuildDate": "Mon, 03 Aug 2026 14:03:17 +0900",
    "total": 1039917,
    "start": 1,
    "display": 1,
    "items": [
        {
            "title": "SK하이닉스 정책 기사",
            "originallink": "https://www.segye.com/newsView/20260803511351",
            "link": "https://n.news.naver.com/mnews/article/022/0004147996",
            "description": "SK하이닉스 관련 기사",
            "pubDate": "Mon, 03 Aug 2026 14:00:00 +0900",
        }
    ],
}


@pytest.fixture
def naver_source() -> dict:
    return {
        "id": str(uuid4()),
        "name": "네이버 뉴스 - SK하이닉스",
        "source_type": "news",
        "config": {"provider": "naver", "query": "SK하이닉스", "request_delay_sec": 0},
    }


def _stub_naver_api(monkeypatch: pytest.MonkeyPatch, payload: dict, status_code: int = 200) -> dict:
    """httpx.get을 가로채 네이버 응답을 대신 준다. 요청 URL·헤더·파라미터를 남긴다."""
    import httpx

    captured: dict = {}

    def fake_get(url: str, **kwargs):
        captured["url"] = url
        captured["params"] = kwargs.get("params", {})
        captured["headers"] = kwargs.get("headers", {})
        return _FakeResponse(payload, status_code)

    monkeypatch.setattr(httpx, "get", fake_get)
    monkeypatch.setenv("NAVER_CLIENT_ID", "test-id-not-real")
    monkeypatch.setenv("NAVER_CLIENT_SECRET", "test-secret-not-real")
    return captured


def test_fetch_naver_news_raises_on_auth_failure(
    monkeypatch: pytest.MonkeyPatch, naver_source: dict, request_obj: CollectRequest
) -> None:
    """
    인증 실패(401 + errorCode)를 status_code 확인 없이 payload.get("items", [])만
    보면 빈 리스트로 조용히 넘어가서 "정상 호출인데 0건 수집"처럼 보인다 —
    반드시 FetchError로 드러나야 한다.
    """
    _stub_naver_api(monkeypatch, NAVER_AUTH_ERROR_RESPONSE, status_code=401)

    with pytest.raises(fetchers.FetchError, match="네이버 검색 API 응답 오류"):
        fetchers.fetch_naver_news(naver_source, request_obj)


def test_fetch_naver_news_succeeds_on_valid_response(
    monkeypatch: pytest.MonkeyPatch, naver_source: dict, request_obj: CollectRequest, stub_article
) -> None:
    _stub_naver_api(monkeypatch, NAVER_SEARCH_RESPONSE)
    stub_article()

    outcome = fetchers.fetch_naver_news(naver_source, request_obj)

    assert len(outcome.items) == 1
    assert outcome.items[0].url == "https://www.segye.com/newsView/20260803511351"


# ------------------------------------------------------------
# NAVER API HUB 전환 (api_variant)
#
# 아래 응답·오류 예시는 공식 문서에 실린 형태를 그대로 옮긴 것이다.
# 실제 API는 호출하지 않는다.
# ------------------------------------------------------------

APIHUB_URL = "https://naverapihub.apigw.ntruss.com/search/v1/news"
LEGACY_URL = "https://openapi.naver.com/v1/search/news.json"

# 검색어와 일치하는 부분이 <b>로 감싸여 오고, 엔티티도 그대로 온다 (문서 명시).
NAVER_MARKUP_RESPONSE = {
    "lastBuildDate": "Thu, 11 Jun 2026 18:34:00 +0900",
    "total": 1039917,
    "start": 1,
    "display": 1,
    "items": [
        {
            "title": "<b>SK하이닉스</b>, HBM4 &quot;양산&quot; 채비…삼성 &amp; 마이크론 추격",
            "originallink": "https://www.segye.com/newsView/20260803511351",
            "link": "https://n.news.naver.com/mnews/article/022/0004147996",
            "description": "<b>SK하이닉스</b>가 HBM4 양산을 &quot;앞당긴다&quot;고 밝혔다.",
            "pubDate": "Thu, 11 Jun 2026 18:34:00 +0900",
        }
    ],
}

# 게이트웨이 계층 오류 — error 객체로 감싸져 온다. errorCode는 HTTP 상태 코드가 아니다.
APIGW_AUTH_ERROR_RESPONSE = {
    "error": {
        "errorCode": "200",
        "message": "Authentication Failed",
        "details": "Authentication information are missing.",
    }
}

# 검색 API 계층 오류 — 평면 구조
SEARCH_API_ERROR_RESPONSE = {
    "errorCode": "SE02",
    "errorMessage": "Invalid display value (부적절한 display 값입니다.)",
}

APIGW_QUOTA_ERROR_RESPONSE = {
    "error": {
        "errorCode": "429",
        "message": "Quota Exceeded",
        "details": "Rate limit exceeded.",
    }
}


def test_naver_apihub_variant_uses_ncp_host_and_headers(
    monkeypatch: pytest.MonkeyPatch, naver_source: dict, request_obj: CollectRequest, stub_article
) -> None:
    """apihub는 NCP 게이트웨이 주소로 가고 X-NCP-* 헤더를 쓴다."""
    naver_source["config"]["api_variant"] = "apihub"
    captured = _stub_naver_api(monkeypatch, NAVER_SEARCH_RESPONSE)
    stub_article()

    fetchers.fetch_naver_news(naver_source, request_obj)

    assert captured["url"] == APIHUB_URL
    assert captured["headers"]["X-NCP-APIGW-API-KEY-ID"] == "test-id-not-real"
    assert captured["headers"]["X-NCP-APIGW-API-KEY"] == "test-secret-not-real"
    # 구 개발자센터 헤더가 같이 나가면 안 된다
    assert "X-Naver-Client-Id" not in captured["headers"]


def test_naver_legacy_variant_uses_developers_host_and_headers(
    monkeypatch: pytest.MonkeyPatch, naver_source: dict, request_obj: CollectRequest, stub_article
) -> None:
    """legacy는 구 개발자센터 주소·헤더를 그대로 쓴다 (2027-06-30 종료 전까지)."""
    naver_source["config"]["api_variant"] = "legacy"
    captured = _stub_naver_api(monkeypatch, NAVER_SEARCH_RESPONSE)
    stub_article()

    fetchers.fetch_naver_news(naver_source, request_obj)

    assert captured["url"] == LEGACY_URL
    assert captured["headers"]["X-Naver-Client-Id"] == "test-id-not-real"
    assert captured["headers"]["X-Naver-Client-Secret"] == "test-secret-not-real"
    assert "X-NCP-APIGW-API-KEY-ID" not in captured["headers"]


def test_naver_api_variant_defaults_to_apihub(
    monkeypatch: pytest.MonkeyPatch, naver_source: dict, request_obj: CollectRequest, stub_article
) -> None:
    """api_variant를 안 적으면 apihub로 간다. 개발자센터는 신규 발급이 막혔다."""
    naver_source["config"].pop("api_variant", None)
    captured = _stub_naver_api(monkeypatch, NAVER_SEARCH_RESPONSE)
    stub_article()

    fetchers.fetch_naver_news(naver_source, request_obj)

    assert captured["url"] == APIHUB_URL
    assert "X-NCP-APIGW-API-KEY-ID" in captured["headers"]


def test_naver_rejects_unknown_api_variant(
    monkeypatch: pytest.MonkeyPatch, naver_source: dict, request_obj: CollectRequest
) -> None:
    naver_source["config"]["api_variant"] = "v3"
    _stub_naver_api(monkeypatch, NAVER_SEARCH_RESPONSE)

    with pytest.raises(fetchers.FetchError, match="알 수 없는 naver api_variant"):
        fetchers.fetch_naver_news(naver_source, request_obj)


def test_naver_extracts_nested_gateway_error(
    monkeypatch: pytest.MonkeyPatch, naver_source: dict, request_obj: CollectRequest
) -> None:
    """
    게이트웨이 오류는 error 객체 안에 중첩돼 있다. payload.get("errorCode")만
    보면 사유가 비어 FetchError 메시지에 원인이 안 남는다.
    """
    _stub_naver_api(monkeypatch, APIGW_AUTH_ERROR_RESPONSE, status_code=401)

    with pytest.raises(fetchers.FetchError) as excinfo:
        fetchers.fetch_naver_news(naver_source, request_obj)

    message = str(excinfo.value)
    assert "Authentication Failed" in message
    assert "Authentication information are missing." in message


def test_naver_extracts_flat_search_api_error(
    monkeypatch: pytest.MonkeyPatch, naver_source: dict, request_obj: CollectRequest
) -> None:
    """검색 API 계층 오류는 평면 구조다. 이쪽도 사유가 드러나야 한다."""
    _stub_naver_api(monkeypatch, SEARCH_API_ERROR_RESPONSE, status_code=400)

    with pytest.raises(fetchers.FetchError) as excinfo:
        fetchers.fetch_naver_news(naver_source, request_obj)

    message = str(excinfo.value)
    assert "SE02" in message
    assert "Invalid display value" in message


def test_naver_quota_exceeded_is_identifiable(
    monkeypatch: pytest.MonkeyPatch, naver_source: dict, request_obj: CollectRequest
) -> None:
    """429는 다른 실패와 구분돼야 "다음 날 재시도"라는 판단을 할 수 있다."""
    _stub_naver_api(monkeypatch, APIGW_QUOTA_ERROR_RESPONSE, status_code=429)

    with pytest.raises(fetchers.FetchError) as excinfo:
        fetchers.fetch_naver_news(naver_source, request_obj)

    assert "하루 호출 한도 초과" in str(excinfo.value)


def test_naver_auth_failure_hints_three_causes(
    monkeypatch: pytest.MonkeyPatch, naver_source: dict, request_obj: CollectRequest
) -> None:
    """401 원인 세 가지가 메시지에 남아야 콘솔에서 어디를 볼지 알 수 있다."""
    _stub_naver_api(monkeypatch, APIGW_AUTH_ERROR_RESPONSE, status_code=401)

    with pytest.raises(fetchers.FetchError) as excinfo:
        fetchers.fetch_naver_news(naver_source, request_obj)

    message = str(excinfo.value)
    assert "키 값" in message
    assert "헤더" in message
    assert "권한" in message


def test_naver_strips_markup_from_title(
    monkeypatch: pytest.MonkeyPatch, naver_source: dict, request_obj: CollectRequest, stub_article
) -> None:
    """<b> 강조 태그와 HTML 엔티티가 documents.title로 새어 들어가면 안 된다."""
    _stub_naver_api(monkeypatch, NAVER_MARKUP_RESPONSE)
    stub_article()

    outcome = fetchers.fetch_naver_news(naver_source, request_obj)

    assert outcome.items[0].title_hint == 'SK하이닉스, HBM4 "양산" 채비…삼성 & 마이크론 추격'


def test_strip_html_handles_tags_and_entities() -> None:
    assert fetchers.strip_html("<b>HBM</b> 양산") == "HBM 양산"
    assert fetchers.strip_html("&quot;A&quot; &amp; &lt;B&gt; &#39;C&#39;") == "\"A\" & <B> 'C'"
    assert fetchers.strip_html(None) is None
    assert fetchers.strip_html("") == ""


@pytest.mark.parametrize(
    ("limit", "expected_display"),
    [(0, 1), (200, 100), (3, 3)],
)
def test_naver_display_is_clamped_to_documented_range(
    monkeypatch: pytest.MonkeyPatch,
    naver_source: dict,
    stub_article,
    limit: int,
    expected_display: int,
) -> None:
    """display는 1~100이다. --limit 0이면 display=0이 나가 SE02가 났다."""
    captured = _stub_naver_api(monkeypatch, NAVER_SEARCH_RESPONSE)
    stub_article()

    fetchers.fetch_naver_news(
        naver_source,
        CollectRequest(workspace_id=uuid4(), source_id=uuid4(), limit=limit),
    )

    assert captured["params"]["display"] == expected_display


def test_naver_limit_zero_collects_nothing_despite_display_floor(
    monkeypatch: pytest.MonkeyPatch, naver_source: dict, stub_article
) -> None:
    """display를 1로 올려도 수집 건수는 limit이 막는다."""
    _stub_naver_api(monkeypatch, NAVER_SEARCH_RESPONSE)
    stub_article()

    outcome = fetchers.fetch_naver_news(
        naver_source, CollectRequest(workspace_id=uuid4(), source_id=uuid4(), limit=0)
    )

    assert outcome.items == []


def test_naver_maps_items_with_originallink_and_rfc822_date(
    monkeypatch: pytest.MonkeyPatch, naver_source: dict, request_obj: CollectRequest, stub_article
) -> None:
    """
    originallink(기사 원문)를 link(네이버 뉴스)보다 우선하고,
    RFC 822 pubDate를 datetime으로 옮긴다. 응답 구조는 두 variant가 같다.
    """
    _stub_naver_api(monkeypatch, NAVER_MARKUP_RESPONSE)
    stub_article()

    outcome = fetchers.fetch_naver_news(naver_source, request_obj)

    item = outcome.items[0]
    assert item.url == "https://www.segye.com/newsView/20260803511351"
    assert item.published_at_hint == datetime(
        2026, 6, 11, 18, 34, 0, tzinfo=timezone(timedelta(hours=9))
    )


# ------------------------------------------------------------
# 구글 뉴스 RSS 링크 디코딩
# ------------------------------------------------------------

GOOGLE_NEWS_LINK = (
    "https://news.google.com/rss/articles/CBMiaEFVX3lxTFBkQVZHdXQwM3VsSl9f"
    "VElHSzlKU3huZHkyZXRITnU1WUF2WXJ0SzNkOEIzX21zN0dHSWVyZ2d5anhfdkRhUVFyUG0x"
    "WkhqRnEyVkRLWGtoTkVVOU03Zmg3ckp1UnlqcFl3?oc=5"
)


def test_resolve_google_news_url_passes_through_non_google_links() -> None:
    url = "https://www.yna.co.kr/view/AKR20260802"
    assert fetchers._resolve_google_news_url(url) == url


def test_resolve_google_news_url_decodes_successfully(monkeypatch: pytest.MonkeyPatch) -> None:
    """
    구글 뉴스 링크는 JS 기반 리다이렉트라 httpx가 못 따라간다 — 언론사 원문
    주소로 디코딩된 값을 써야 전처리 단계에서 빈 정제 결과가 안 나온다.
    """
    import googlenewsdecoder

    monkeypatch.setattr(
        googlenewsdecoder,
        "gnewsdecoder",
        lambda url, interval=1: {"status": True, "decoded_url": "https://www.mt.co.kr/stock/2026/08/03/x"},
    )

    resolved = fetchers._resolve_google_news_url(GOOGLE_NEWS_LINK)

    assert resolved == "https://www.mt.co.kr/stock/2026/08/03/x"


def test_resolve_google_news_url_raises_when_decoder_reports_failure(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """
    구글 주소로 폴백하면 그 값이 canonical_url에 저장돼 같은 기사가 원문 주소로
    다시 들어왔을 때 별개 문서가 된다. 폴백 대신 항목을 버린다.
    """
    import googlenewsdecoder

    monkeypatch.setattr(
        googlenewsdecoder, "gnewsdecoder", lambda url, interval=1: {"status": False, "message": "boom"}
    )

    with pytest.raises(fetchers.UnresolvedURLError):
        fetchers._resolve_google_news_url(GOOGLE_NEWS_LINK)


def test_resolve_google_news_url_raises_when_decoder_raises(monkeypatch: pytest.MonkeyPatch) -> None:
    """디코더가 죽어도 수집 자체는 안 죽어야 한다 — 소스가 아니라 항목 1건만 버린다."""
    import googlenewsdecoder

    def boom(url, interval=1):
        raise RuntimeError("network down")

    monkeypatch.setattr(googlenewsdecoder, "gnewsdecoder", boom)

    with pytest.raises(fetchers.UnresolvedURLError):
        fetchers._resolve_google_news_url(GOOGLE_NEWS_LINK)


def test_unresolved_url_error_is_not_a_fetch_error() -> None:
    """
    소스 전체 실패(FetchError)와 구분돼야 한다. 섞이면 항목 1건 때문에
    소스 job이 failed로 남는다.
    """
    assert not issubclass(fetchers.UnresolvedURLError, fetchers.FetchError)


def test_fetch_article_resolves_google_news_link_before_http_get(
    monkeypatch: pytest.MonkeyPatch, stub_article
) -> None:
    """_fetch_article이 실제로 디코딩된 주소로 _http_get을 호출하는지 확인한다."""
    import googlenewsdecoder

    monkeypatch.setattr(
        googlenewsdecoder,
        "gnewsdecoder",
        lambda url, interval=1: {"status": True, "decoded_url": "https://www.mt.co.kr/stock/2026/08/03/x"},
    )
    calls = stub_article()

    item = fetchers._fetch_article({"name": "구글 RSS"}, GOOGLE_NEWS_LINK, None, None)

    assert calls == ["https://www.mt.co.kr/stock/2026/08/03/x"]


def test_fetch_article_rejects_final_url_that_is_still_google(
    monkeypatch: pytest.MonkeyPatch, stub_article
) -> None:
    """디코딩은 됐는데 리다이렉트가 구글로 되돌아오면 canonical_url로 쓸 수 없다."""
    import googlenewsdecoder

    monkeypatch.setattr(
        googlenewsdecoder,
        "gnewsdecoder",
        lambda url, interval=1: {"status": True, "decoded_url": "https://www.mt.co.kr/stock/x"},
    )
    stub_article({"https://www.mt.co.kr/stock/x": GOOGLE_NEWS_LINK})

    with pytest.raises(fetchers.UnresolvedURLError):
        fetchers._fetch_article({"name": "구글 RSS"}, GOOGLE_NEWS_LINK, None, None)


GOOGLE_RSS_FEED = f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"><channel><title>구글 뉴스</title>
<item><title>SK하이닉스 기사</title><link>{GOOGLE_NEWS_LINK}</link>
<pubDate>Mon, 03 Aug 2026 07:04:00 GMT</pubDate></item>
</channel></rss>"""


def test_fetch_rss_skips_item_when_google_url_unresolved(
    monkeypatch: pytest.MonkeyPatch, request_obj: CollectRequest
) -> None:
    """
    디코딩 실패 항목은 문서를 만들지 않고 사유만 남긴다. 구글 주소가
    canonical_url로 저장되면 같은 기사가 원문 주소로 다시 들어와도 별개 문서가 된다.
    """
    import googlenewsdecoder

    monkeypatch.setattr(
        googlenewsdecoder, "gnewsdecoder", lambda url, interval=1: {"status": False, "message": "boom"}
    )
    monkeypatch.setattr(
        fetchers, "_http_get", lambda url, source: (GOOGLE_RSS_FEED.encode(), "application/xml", 200, url)
    )
    source = {"name": "구글 RSS", "source_type": "rss", "base_url": "https://news.google.com/rss/search?q=x"}

    outcome = fetchers.fetch_rss(source, request_obj)

    assert outcome.items == []
    assert outcome.skip_reasons == {"google_url_unresolved": 1}


def test_fetch_rss_collects_item_when_google_url_decodes(
    monkeypatch: pytest.MonkeyPatch, request_obj: CollectRequest
) -> None:
    """디코딩에 성공하면 언론사 원문 주소가 문서 식별자가 된다."""
    import googlenewsdecoder

    monkeypatch.setattr(
        googlenewsdecoder,
        "gnewsdecoder",
        lambda url, interval=1: {"status": True, "decoded_url": "https://www.mt.co.kr/stock/2026/08/03/x"},
    )

    def fake_http_get(url: str, source: dict):
        if "news.google.com/rss/search" in url:
            return GOOGLE_RSS_FEED.encode(), "application/xml", 200, url
        return ARTICLE_HTML, "text/html", 200, url

    monkeypatch.setattr(fetchers, "_http_get", fake_http_get)
    source = {"name": "구글 RSS", "source_type": "rss", "base_url": "https://news.google.com/rss/search?q=x"}

    outcome = fetchers.fetch_rss(source, request_obj)

    assert outcome.skip_reasons == {}
    assert len(outcome.items) == 1
    assert outcome.items[0].url == "https://www.mt.co.kr/stock/2026/08/03/x"


# ------------------------------------------------------------
# DART 공시 수집기 (disclosure)
#
# list.json / document.xml 응답 구조는 2026-08-05에 실제 DART Open API를
# 호출해 확인한 형태를 그대로 옮겼다(값은 예시로 바꿈).
# ------------------------------------------------------------

DART_LIST_RESPONSE = {
    "status": "000",
    "message": "정상",
    "list": [
        {
            "corp_code": "00164779",
            "corp_name": "SK하이닉스",
            "stock_code": "000660",
            "report_nm": "연결재무제표기준영업(잠정)실적(공정공시)",
            "rcept_no": "20260729800013",
            "flr_nm": "SK하이닉스",
            "rcept_dt": "20260729",
            "rm": "유",
        }
    ],
}

DART_NO_DATA_RESPONSE = {"status": "013", "message": "조회된 데이타가 없습니다."}
DART_AUTH_ERROR_RESPONSE = {"status": "010", "message": "등록되지 않은 키입니다."}


def _zip_bytes(files: dict[str, bytes]) -> bytes:
    import io
    import zipfile

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        for name, content in files.items():
            zf.writestr(name, content)
    return buf.getvalue()


DART_DOCUMENT_ZIP = _zip_bytes({"20260729800013.xml": b"<html><body>\xec\x8b\xa4\xec\xa0\x81 \xeb\xb0\x9c\xed\x91\x9c</body></html>"})


@pytest.fixture
def disclosure_source() -> dict:
    return {
        "id": str(uuid4()),
        "name": "DART - SK하이닉스",
        "source_type": "disclosure",
        "config": {"corp_code": "00164779", "request_delay_sec": 0},
    }


def _stub_dart_api(
    monkeypatch: pytest.MonkeyPatch,
    list_payload: dict,
    list_status: int = 200,
    document_content: bytes = DART_DOCUMENT_ZIP,
    document_status: int = 200,
) -> dict:
    """httpx.get을 가로채 list.json/document.xml 두 엔드포인트를 URL로 갈라서 응답한다."""
    import httpx

    captured: dict = {"list_calls": [], "document_calls": []}

    def fake_get(url: str, **kwargs):
        if url == fetchers.DART_LIST_URL:
            captured["list_calls"].append(kwargs.get("params", {}))
            return _FakeResponse(list_payload, list_status)
        if url == fetchers.DART_DOCUMENT_URL:
            captured["document_calls"].append(kwargs.get("params", {}))
            return _FakeResponse({}, document_status, content=document_content)
        raise AssertionError(f"예상하지 못한 URL 호출: {url}")

    monkeypatch.setattr(httpx, "get", fake_get)
    monkeypatch.setenv("DART_API_KEY", "test-key-not-real")
    return captured


def test_fetch_disclosure_raises_without_corp_code(
    monkeypatch: pytest.MonkeyPatch, request_obj: CollectRequest
) -> None:
    monkeypatch.setenv("DART_API_KEY", "test-key-not-real")
    source = {"id": str(uuid4()), "name": "DART", "source_type": "disclosure", "config": {}}

    with pytest.raises(fetchers.FetchError, match="corp_code"):
        fetchers.fetch_disclosure(source, request_obj)


def test_fetch_disclosure_raises_without_api_key(
    monkeypatch: pytest.MonkeyPatch, disclosure_source: dict, request_obj: CollectRequest
) -> None:
    monkeypatch.delenv("DART_API_KEY", raising=False)

    with pytest.raises(fetchers.FetchError, match="DART_API_KEY"):
        fetchers.fetch_disclosure(disclosure_source, request_obj)


def test_fetch_disclosure_raises_on_auth_error(
    monkeypatch: pytest.MonkeyPatch, disclosure_source: dict, request_obj: CollectRequest
) -> None:
    _stub_dart_api(monkeypatch, DART_AUTH_ERROR_RESPONSE)

    with pytest.raises(fetchers.FetchError, match="DART 공시검색 API 응답 오류"):
        fetchers.fetch_disclosure(disclosure_source, request_obj)


def test_fetch_disclosure_returns_empty_on_no_data_status(
    monkeypatch: pytest.MonkeyPatch, disclosure_source: dict, request_obj: CollectRequest
) -> None:
    """status='013'(조회된 데이타 없음)은 에러가 아니라 빈 결과다."""
    _stub_dart_api(monkeypatch, DART_NO_DATA_RESPONSE)

    outcome = fetchers.fetch_disclosure(disclosure_source, request_obj)

    assert outcome.items == []
    assert outcome.skip_reasons == {}


def test_fetch_disclosure_extracts_document_and_uses_viewer_url_as_canonical(
    monkeypatch: pytest.MonkeyPatch, disclosure_source: dict, request_obj: CollectRequest
) -> None:
    """
    본문은 document.xml(zip 안 HTML)에서 오지만, canonical_url은 사람이 클릭해서
    보는 main.do 뷰어 주소여야 한다 — main.do 자체는 JS로 본문을 늦게 채우는
    frameset이라 body로 못 쓴다.
    """
    _stub_dart_api(monkeypatch, DART_LIST_RESPONSE)

    outcome = fetchers.fetch_disclosure(disclosure_source, request_obj)

    assert len(outcome.items) == 1
    item = outcome.items[0]
    assert item.url == "https://dart.fss.or.kr/dsaf001/main.do?rcpNo=20260729800013"
    assert item.content_type == "text/html"
    assert b"<html>" in item.body
    assert item.title_hint == "연결재무제표기준영업(잠정)실적(공정공시)"
    assert item.published_at_hint == datetime(2026, 7, 29, tzinfo=timezone.utc)


def test_fetch_disclosure_skips_filings_older_than_since(
    monkeypatch: pytest.MonkeyPatch, disclosure_source: dict
) -> None:
    _stub_dart_api(monkeypatch, DART_LIST_RESPONSE)
    request = CollectRequest(
        workspace_id=uuid4(), source_id=uuid4(), since=datetime(2026, 7, 30, tzinfo=timezone.utc)
    )

    outcome = fetchers.fetch_disclosure(disclosure_source, request)

    assert outcome.items == []
    assert outcome.skip_reasons == {"older_than_since": 1}


def test_fetch_disclosure_skips_blocked_document_response(
    monkeypatch: pytest.MonkeyPatch, disclosure_source: dict, request_obj: CollectRequest
) -> None:
    _stub_dart_api(monkeypatch, DART_LIST_RESPONSE, document_status=404, document_content=b"")

    outcome = fetchers.fetch_disclosure(disclosure_source, request_obj)

    assert outcome.items == []
    assert outcome.skip_reasons == {"blocked_or_empty": 1}


def test_fetch_disclosure_sends_corp_code_and_date_range(
    monkeypatch: pytest.MonkeyPatch, disclosure_source: dict
) -> None:
    captured = _stub_dart_api(monkeypatch, DART_NO_DATA_RESPONSE)
    request = CollectRequest(
        workspace_id=uuid4(), source_id=uuid4(), since=datetime(2026, 7, 1, tzinfo=timezone.utc)
    )

    fetchers.fetch_disclosure(disclosure_source, request)

    params = captured["list_calls"][0]
    assert params["corp_code"] == "00164779"
    assert params["bgn_de"] == "20260701"
    assert params["crtfc_key"] == "test-key-not-real"


def test_gnews_skips_non_english_or_korean_language_before_fetch(
    monkeypatch: pytest.MonkeyPatch, gnews_source: dict, request_obj: CollectRequest, stub_article
) -> None:
    payload = {
        "totalArticles": 1,
        "articles": [
            {
                "title": "Vietnam semiconductor update",
                "url": "https://example.com/vi-news",
                "publishedAt": "2026-08-02T13:50:15Z",
                "lang": "vi",
            }
        ],
    }
    _stub_gnews_api(monkeypatch, payload)
    article_calls = stub_article()

    outcome = fetchers.fetch_gnews(gnews_source, request_obj)

    assert outcome.items == []
    assert outcome.skip_reasons == {"unsupported_language": 1}
    assert article_calls == []


def test_fetch_rss_skips_non_english_or_korean_article_language(
    monkeypatch: pytest.MonkeyPatch, request_obj: CollectRequest
) -> None:
    feed = """<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"><channel><title>Feed</title>
<item><title>Vietnam semiconductor update</title><link>https://example.com/vi-news</link>
<pubDate>Mon, 03 Aug 2026 07:04:00 GMT</pubDate></item>
</channel></rss>"""
    article_html = b'<html lang="vi"><body><article>Vietnam semiconductor update</article></body></html>'

    def fake_http_get(url: str, source: dict):
        if url == "https://example.com/rss":
            return feed.encode(), "application/xml", 200, url
        return article_html, "text/html", 200, url

    monkeypatch.setattr(fetchers, "_http_get", fake_http_get)
    source = {"name": "RSS", "source_type": "rss", "base_url": "https://example.com/rss"}

    outcome = fetchers.fetch_rss(source, request_obj)

    assert outcome.items == []
    assert outcome.skip_reasons == {"unsupported_language": 1}


def test_fetch_disclosure_attaches_request_type_metadata(
    monkeypatch: pytest.MonkeyPatch, request_obj: CollectRequest
) -> None:
    import httpx

    captured_types: list[str | None] = []

    def fake_get(url: str, **kwargs):
        url = str(url)
        params = kwargs.get("params", {})
        if url == fetchers.DART_LIST_URL:
            disclosure_type = params.get("pblntf_ty")
            captured_types.append(disclosure_type)
            if disclosure_type == "B":
                return _FakeResponse({
                    "status": "000",
                    "list": [{
                        "rcept_no": "20260812000001",
                        "report_nm": "Major issue report",
                        "rcept_dt": "20260812",
                    }],
                })
            if disclosure_type == "D":
                return _FakeResponse({
                    "status": "000",
                    "list": [{
                        "rcept_no": "20260812000002",
                        "report_nm": "Equity disclosure",
                        "rcept_dt": "20260811",
                    }],
                })
            return _FakeResponse({"status": "013", "message": "no data"})
        raise AssertionError(url)

    monkeypatch.setattr(httpx, "get", fake_get)
    monkeypatch.setenv("DART_API_KEY", "test-key")
    def fake_document(source, api_key, rcept_no, report_name, published_at, disclosure_type_code=None):
        return RawFetchResult(
            source_name=source["name"],
            url=f"{fetchers.DART_VIEWER_URL}?rcpNo={rcept_no}",
            fetched_at=datetime.now(timezone.utc),
            content_type="text/html",
            body=b"<p>body</p>",
            title_hint=report_name,
            published_at_hint=published_at,
            metadata={
                "dart_rcept_no": rcept_no,
                "dart_disclosure_type_code": disclosure_type_code,
                "dart_disclosure_type_name": fetchers.DART_DISCLOSURE_TYPE_NAMES.get(disclosure_type_code or ""),
            },
        )

    monkeypatch.setattr(fetchers, "_fetch_disclosure_document", fake_document)
    source = {
        "id": str(uuid4()),
        "name": "DART",
        "source_type": "disclosure",
        "config": {"corp_code": "00164779", "request_delay_sec": 0},
    }

    outcome = fetchers.fetch_disclosure(source, request_obj)

    assert captured_types == list(fetchers.DART_DISCLOSURE_TYPES)
    assert [item.metadata["dart_disclosure_type_code"] for item in outcome.items] == ["B", "D"]
    assert [item.metadata["dart_disclosure_type_name"] for item in outcome.items] == ["주요사항보고", "지분공시"]


def test_fetch_article_rejects_soft_block_redirect(stub_article) -> None:
    """
    200으로 위장한 차단. se-cu.com은 봇에게 403을 주는 대신 안내 페이지로 보내고
    그걸 200으로 돌려줬다(2026-08-12). 상태 코드 검사로는 안 잡힌다.

    막지 않으면 그 안내 주소가 canonical_url이 되고, 그 도메인에서 차단당한
    기사가 전부 한 문서로 뭉친다(uq_documents_workspace_url).
    """
    article = "http://se-cu.com/news/articleView.html?idxno=1"
    stub_article({article: "http://se-cu.com/ndsoft/error.html"})

    assert fetchers._fetch_article({"name": "se-cu"}, article, None, None) is None


def test_fetch_article_keeps_article_url_that_merely_contains_error(stub_article) -> None:
    """'error'를 부분 문자열로 찾으면 멀쩡한 기사가 걸린다. 이름 전체로만 판정한다."""
    article = "https://www.mt.co.kr/news/1"
    redirected = "https://www.mt.co.kr/news/error-correction-code-hbm"
    stub_article({article: redirected})

    item = fetchers._fetch_article({"name": "머니투데이"}, article, None, None)

    assert item is not None and item.url == redirected


def test_fetch_article_keeps_url_that_was_not_redirected(stub_article) -> None:
    """리다이렉트가 없었으면 소프트 차단 판정 대상이 아니다."""
    article = "https://www.mt.co.kr/news/error.html"
    stub_article()

    assert fetchers._fetch_article({"name": "머니투데이"}, article, None, None) is not None
